### ISSUE TITLE
Memory Leak on Errors

### ISSUE THREAD

**Issue by JCMais** [unreleased/request-curl#5]
The on error listener here: https://github.com/unreleased/request-curl/blob/a272113d5fc803d6c74b4092be2443cfae3926c4/index.js#L342-L345

Is not really closing the curl handle, it's just calling bind on the close function.

**Comment by unreleased** [comment]
Thank you! I will push a fix shortly. I believe this must also be what was causing TCP sockets to be left open and my server to crash :(

**Comment by unreleased** [comment]
Rewrote and fixed issues now I have more time x
